"""
Constants from the csv
"""

STATES = [
    "Ohio",
    "Washington",
    "Massachusetts",
    "New Mexico",
    "Indiana",
    "Kansas",
    "Wisconsin",
    "New Hampshire",
    "Rhode Island",
    "Maryland",
    "Nebraska",
    "West Virginia",
    "Tennessee",
    "Vermont",
    "Arizona",
    "Connecticut",
    "Pennsylvania",
    "National",
    "North Dakota",
    "Michigan",
    "Illinois",
    "Oklahoma",
    "Idaho",
    "Iowa",
    "Arkansas",
    "Missouri",
    "Utah",
    "Maine",
    "Puerto Rico",
    "Louisiana",
    "Georgia",
    "Wyoming",
    "Guam",
    "South Carolina",
    "Alaska",
    "Virginia",
    "California",
    "South Dakota",
    "Oregon",
    "District of Columbia",
    "New York",
    "Montana",
    "North Carolina",
    "Delaware",
    "Mississippi",
    "Florida",
    "Hawaii",
    "Kentucky",
    "Minnesota",
    "Alabama",
    "Virgin Islands",
    "Colorado",
    "New Jersey",
    "Texas",
    "Nevada",
]

QUESTIONS = [
    "Percent of adults aged 18 years and older who have an overweight classification",
    "Percent of adults aged 18 years and older who have obesity",
    "Percent of adults who engage in no leisure-time physical activity",
    "Percent of adults who report consuming fruit less than one time daily",
    "Percent of adults who report consuming vegetables less than one time daily",
    "Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)",
    "Percent of adults who achieve at least 150 minutes a week of moderate-intensity aerobic physical activity or 75 minutes a week of vigorous-intensity aerobic physical activity and engage in muscle-strengthening activities on 2 or more days a week",
    "Percent of adults who achieve at least 300 minutes a week of moderate-intensity aerobic physical activity or 150 minutes a week of vigorous-intensity aerobic activity (or an equivalent combination)",
    "Percent of adults who engage in muscle-strengthening activities on 2 or more days a week",
]

QUESTIONS_BEST_IS_MIN = [
    "Percent of adults aged 18 years and older who have an overweight classification",
    "Percent of adults aged 18 years and older who have obesity",
    "Percent of adults who engage in no leisure-time physical activity",
    "Percent of adults who report consuming fruit less than one time daily",
    "Percent of adults who report consuming vegetables less than one time daily",
]
